# Generated by Django 3.2.4 on 2021-11-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='randomUser', max_length=30),
        ),
    ]
